---
    - name: Install MariaDB and it's dependencies - RedHat
      yum: 
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - mariadb
        - mariadb-server
        - mariadb-devel
        - MySQL-python
        - php-mysql
      when: ansible_os_family == "RedHat"
      notify:
        - open_mariadb_port

    - name: Install MariaDB and it's dependencies - Debian
      apt: 
        name: "{{ item }}"
        update_cache: yes
        upgrade: yes
        state: latest
      with_items:
       # Apt Packages
      when: ansible_os_family == "Debian"
      notify:
        - open_mariadb_port

    - name: Enable MariaDB
      systemd: 
        name: mariadb
        state: started
        enabled: yes
      changed_when: true
      notify:
        - restart_mariadb
